### ISSUE TITLE
<BD+>...<BD>

### ISSUE THREAD

**Issue by gerritbruening** [gerritbruening/TXSTEP#14]
```
kochenden Blase, die in einem Gefäß ruht<BD+>, <BD>das<BD+> <BD>aus dem dauerhaften Stoff von Häusern
```

Völlig unbedeutend? Beide `<BD>` werden [im Moment](https://github.com/gerritbruening/TXSTEP/blob/6de40f4d47e543d86c072ee14c45dcf23686818a/fff2xml.xml#L87) ersatzlos getilgt:

```
kochenden Blase, die in einem Gefäß ruht, das aus dem dauerhaften Stoff von Häusern
```

**Comment by gerritbruening** [comment]
@Wfanta, können Sie einmal schauen, ob die Tilgung von `<BD+>` und `<BD>` korrekt ist?

**Comment by Wfanta** [comment]
<BD+> <BD> ist völlig redundant! Ich hab mir das angesehen, kann mir nicht erklären, was es ist bzw. wie es zustande kommt. Möglicherweise stammt es aus einer Ursprungsdatei vor FolioViews und wurde beim Import so umgesetzt. Es ist aber sehr wichtig, dass wir die redundanten Codes ausfindig machen. Das hilft sehr bei späteren Migrationsprozessen. DANKE!

**Comment by gerritbruening** [comment]
Danke für die Klärung. Laut http://folio.wikidot.com/ bedeutet `<BD>` übrigens "Bold", also "fett".

**Comment by Wfanta** [comment]
Danke für den sehr wichtigen Hinweis. Wir benötigen letztlich für die Weiterarbeit eine Liste aller Kodierungen, die in unserem Flatfile vorkommen.

**Comment by gerritbruening** [comment]
[Ist notiert](https://github.com/gerritbruening/TXSTEP/issues/29)!
