### ISSUE TITLE
Seitenanfang = Kapitelanfang

### ISSUE THREAD

**Issue by gerritbruening** [gerritbruening/TXSTEP#20]
Beispiel aus FFF:

```
<RD:"ÜBERSCHRIFT 4"><FD:"S-KAPITEL"><JL:"LESETEXT TITEL","KK-1/5"><JD:"MoE-1/5">5. Ulrich</FD:"S-KAPITEL"><EL>
<RD:"ÜBERSCHRIFT 7">[Seite 24]
<RD><PS:"LESETEXT DRUCK"><TS:3.28056,RT,NO>Der Mann ...
```

Der Seitenumbruch befindet sich **vor** und nicht **nach** der Kapitelüberschrift.

Liste der Seitenanfänge, die mit einem Kapitelanfang zusammenfallen:
https://github.com/gerritbruening/TXSTEP/blob/6de40f4d47e543d86c072ee14c45dcf23686818a/fff2xml.xml#L11

**Comment by gerritbruening** [comment]
Frage: Ist [diese Liste ](https://github.com/gerritbruening/TXSTEP/blob/6de40f4d47e543d86c072ee14c45dcf23686818a/fff2xml.xml#L11) korrekt?

**Comment by gerritbruening** [comment]
Lieber Herr @Wfanta , darf ich Sie fragen, ob die [diese Liste ](https://github.com/gerritbruening/TXSTEP/blob/6de40f4d47e543d86c072ee14c45dcf23686818a/fff2xml.xml#L11) der mutmaßlichen Fälle für Seitenanfang = Kapitelanfang korrekt ist und das Thema also als erledigt markiert werden kann?

**Comment by Wfanta** [comment]
Ich habe das jetzt überprüft. Die Liste ist korrekt. Nur Seite 9 = Anfang Kapitel 1 fehlt.

**Comment by gerritbruening** [comment]
Gut, danke!
