### ISSUE TITLE
"ND1989" in MoE1_Varianten2

### ISSUE THREAD

**Issue by gerritbruening** [gerritbruening/TXSTEP#23]
Was bedeutet `{yy|ND1989|}` und wie soll es verarbeitet werden?

**Bitte an WF**: Präambel von MoE1_Varianten2.docx ergänzen.

**Comment by Wfanta** [comment]
|ND1989| bedeutet Neudruck 1990 (der Frisé-Ausgabe), bezieht sich auf den Anmerkungsteil, nur der wurde im Verhältnis zur Ausgabe 1978 ergänzt.

**Comment by gerritbruening** [comment]
`{yy|ND1989|}` wird nun in `<Komm ref="#yy|ND1989|"/>` umgesetzt, ist das erstmal in Ordnung?

Zu gegebener Zeit sollte der Abschnitt `DEFINITIONEN` entsprechend ergänzt werden.

**Comment by Wfanta** [comment]
Ja genau, das ist in Ordnung! Wir werden dann den Abschnitt Definitionen gemeinsam bearbeiten, da gibt es gewiss noch mehr zu ändern...
