### ISSUE TITLE
Bedeutung und Behandlung von |Nullvarianz|

### ISSUE THREAD

**Issue by gerritbruening** [gerritbruening/TXSTEP#25]
Lieber @Wfanta, könnten Sie hier zunächst kurz erläutern, was Sie mit Nullvarianz meinen?

**Comment by Wfanta** [comment]
Mit Nullvarianz wollte ich vermerken, dass die Variantenkennzeichnung in der KA gegenstandslos ist, weil tatsächlich keine Varianz besteht, oder dass die Variantenkennzeichnung in der KA fehlt. Es sind also tatsächlich zwei verschiedene Fälle, aus dem Kontext auseinander zu halten.

**Comment by gerritbruening** [comment]
```
[Seite 54] {„der Wind“|Nullvarianz}
```

bedeutet also, die EA hat in Wirklichkeit nicht "derWind", wie das Flatfile sagt, sondern wie alle anderen Zeugen auch "der Wind"?

Und

`[Seite 90] {„alle“|Nullvarianz|} {HE: „alle“|Pfeil, Fragezeichen|}`

bedeutet, dass alle Zeugen außer dem Handexemplar den Wortlaut "alle" haben?

`[Seite 140] <EA>würde</EA> {HE: |Haken|} <RA>würde</RA> {KA: |Nullvarianz|} <GA>würde</GA> <Komm ref="#bb"/>`

bedeutet, dass auch in der KA "würde" steht?

Aber was heißt

`[Seite 1067] {EA: "ENDE DES ERSTEN BUCHES"} {RA: |Nullvarianz|} {KA: "Ende des ersten Buches"} {GA+!: |Nullvarianz|}`?

Wären Sie bereit, alle bis auf den ersten Fall doch auszuschreiben? Das würde die Umwandlung sehr erleichtern.

**Comment by Wfanta** [comment]
Nullvarianz ist von mir bestimmt falsch gewählt. Um klar zu machen, was jeweils in den Ausgaben steht, braucht es vielleicht einen Kommentar.

[Seite 54] {„der Wind“|Nullvarianz} --> im Scan/OCR der EA entstand „derWind“ = pingelige Lesart der KA (s. Faksimile im Dateianhang)
[Seite 90] {„alle“|Nullvarianz|} {HE: „alle“|Pfeil, Fragezeichen|} --> Es geht hier nicht um die Verzeichnung einer Varianz, sondern einer nicht-varianz-wertigen Handexemplareintragung.
[Seite 140] <EA>würde</EA> {HE: |Haken|} <RA>würde</RA> {KA: |Nullvarianz|} <GA>würde</GA> <Komm ref="#bb"/> --> In der KA wurde übersehen, den Haken beim „würde“ im HE zu verzeichnen.
[Seite 1067] {EA: "ENDE DES ERSTEN BUCHES"} {RA: |Nullvarianz|} {KA: "Ende des ersten Buches"} {GA+!: |Nullvarianz|} --> In der RA und in der GA steht da nichts!

Können Sie bitte Vorschläge für TEI-konforme Auszeichnung für diese vier voneinander verschiedenen Fälle entwickeln?

**Comment by gerritbruening** [comment]
Zu
`[Seite 90] {„alle“|Nullvarianz|} {HE: „alle“|Pfeil, Fragezeichen|}`
Hier würde ich vorschlagen, dass Sie `{„alle“|Nullvarianz|}` ausschreiben, beginnend mit `{EA: „alle“}` usw.

**Comment by gerritbruening** [comment]
Zu
`[Seite 140] <EA>würde</EA> {HE: |Haken|} <RA>würde</RA> {KA: |Nullvarianz|} <GA>würde</GA> <Komm ref="#bb"/>` und

> --> In der KA wurde übersehen, den Haken beim „würde“ im HE zu verzeichnen.

Die Apparateinträge verzeichnen Lesarten von Ausgaben, nicht oder nur in zweiter Linie die Apparateinträge in anderen Ausgaben. Deswegen würde ich zunächst gern wissen, welche Lesart HE und KA haben, also `{HE: „würde“|Haken|}` und `{KA: „würde“}`. Die Information über den in der KA fehlenden Apparateintrag würde ich wie "Haken" als Kommentar geben, also z.B. `{KA: „würde“|Apparateintrag fehlt|}`. Oder Sie führen einen neuen Kommentar wie `{xyz-}`, etwa des Sinns: "Die Eintragung im Handexemplar ist in der Klagenfurter Ausgabe nicht dokumentiert".

**Comment by gerritbruening** [comment]
Zu
`[Seite 1067] {EA: "ENDE DES ERSTEN BUCHES"} {RA: |Nullvarianz|} {KA: "Ende des ersten Buches"} {GA+!: |Nullvarianz|}` und

> --> In der RA und in der GA steht da nichts! 

würde ich vorschlagen:
--> `{RA: |fehlt|}`
--> `{GA+!: |fehlt|}`

**Comment by gerritbruening** [comment]
Zu

> [Seite 54] {„der Wind“|Nullvarianz}

Lieber @Wfanta, könnten Sie hier bitte den fehlenden | hinter "Nullvarianz" ergänzen?

**Comment by gerritbruening** [comment]
Wir haben jetzt noch dreimal `{KA: |Nullvarianz|}`. Lieber @Wfanta, mögen Sie hier bitte die entsprechende Lesart einfügen? Im XML entsteht sonst
`<RA>würde</RA> <KA><note type="editorial">Nullvarianz</note></KA>`
was mir inkonsistent zu sein scheint.

**Comment by Wfanta** [comment]
Ich habe diese drei verbleibende Fälle nun richtig gestellt zu:
{KA: „würde“|ohne Auszeichnung|}
