### ISSUE TITLE
Deckungsgleichheit von <KA> in FF und ...Varianten.txt

### ISSUE THREAD

**Issue by gerritbruening** [gerritbruening/TXSTEP#27]
Lieber @Wfanta, gibt es neben dem neulich [hier](https://github.com/gerritbruening/TXSTEP/issues/22#issuecomment-243434546) genannten Fall (dem siebten Eintrag) weitere Einträge, wo in Ihrer Liste der Bereich der Varianten ausgeweitet oder sonst verändert wurde?

(Hintergrund: `<KA>` in beiden Dateien wird das Vehikel für Zuordnung und Ersetzung sein.)

**Comment by Wfanta** [comment]
Ich glaube nicht, müsste aber alle Einträge noch einmal kontrollieren. Wie ist das mit dem Vehikel für Zuordnung und Ersetzung ganz genau gemeint?

**Comment by gerritbruening** [comment]
Bsp.: Der erste Apparateintrag im Flatfiletext lautet nach der Umwandlung:
`<RA>früher</RA> <KA>früher,</KA>`
Der erste Apparateintrag Ihrer Liste lautet nach der Umwandlung:
`<EA>früher,</EA> <RA>früher</RA> <KA>früher,</KA> <GA>früher,</GA> <Komm ref="#cc"/> <Komm ref="#zz"/>`
Nun vergleicht ein Programm die Einträge miteinander und stellt die Unterschiede fest. Die festgestellten Unterschiede werden als Korrekturen auf den Flatfiletext angewendet.
