### ISSUE TITLE
[Seite 88] |SB|nicht|AB| |GA+!|

### ISSUE THREAD

**Issue by gerritbruening** [gerritbruening/TXSTEP#30]
Lieber @Wfanta, könnten Sie mir diese Einträge erläutern?

Was hat die EA, was die GA, und warum?

**Comment by Wfanta** [comment]
Das bedeutet, EA Seite 88 Seitenbeginn ist kein Absatzbeginn, das musste in der GA richtig gestellt werden, d.h. der dort auf Grund der KA vorhandene Absatzbeginn wurde entfernt. (In der KA beginnt jede EA-Seite mit einem neuen Absatz. In der Variantenliste ist festgehalten, wo in der EA tatsächlich ein Absatzbeginn mit dem Seitenbeginn zusammen fällt und - |SB=AB| - und wo nach dem Transfer KA --> GA trotz händischer Bearbeitung fälschlicherweise ein Absatzbeginn steht - |SB|nicht|AB|.

**Comment by gerritbruening** [comment]
Danke für die Erklärung. Dann würde ich diese Einträge raten hintan zu stellen, da 
1. es in der KA ja nicht so gemeint ist, dass Absätze da sind, es sieht nur so aus.
2. noch viel mehr solcher "Absätze" weggefallen sind. Bei Gelegenheit kann ich mal zählen.

Verzeichnen würde ich nur den einen falschen Absatz in der GA.

**Comment by Wfanta** [comment]
Lieber Herr Brüning,

wie genau meinen Sie das mit „hintanstellen“? Soll ich diese Anträge aus der Varianten-Datei löschen.
LG WFanta

**Comment by gerritbruening** [comment]
Löschen muss nicht sein, wir können ja bei späterer Gelegenheit auf diese Fälle noch einmal zurückkommen.
